### ISSUE TITLE
LD package review

### ISSUE THREAD

**Issue by Lukas-DeFilippo-NOAA** [afsc-gap-products/coldpool#23]
Package is great. Like Stan, I found everything installed fine after updating R. I encountered similar errors as Stan already noted with the following code chunk:

interpolation_wrapper(temp_data_path = ebs_csv_path,
                       proj_crs = proj_crs,
                       cell_resolution = 5000, # 5x5 km grid resolution
                       select_years = 1982,year(Sys.Date()), 
                       interp_variable = "gear_temperature",
                       select_region = "sebs") 
Error in interpolation_wrapper(temp_data_path = ebs_csv_path, proj_crs = proj_crs,  : 
  unused argument (year(Sys.Date()))

Deleting 1982 didn't work for me, I'm guessing because the current year is 2022 and there's no data for 2022 yet so I just entered a year manually and that worked. 

I also encountered the error that Stan noted here
save(cpa_pre2021, 
        ebs_proj_crs, 
        cold_pool_index,
        nbs_mean_temperature,
        ebs_bottom_temperature,
        ebs_surface_temperature,
        nbs_ebs_bottom_temperature,
        nbs_ebs_surface_temperature,
        file = here::here("R", "sysdata.rda"))
 }
 'No such file or directory'Error in gzfile(file, "wb") : cannot open the connection
And was able to resolve it by following his steps of creating a folder and moving sysdata.rda there manually.

I'm not sure If I was supposed to run this part I got this error message when trying to update the documentation:
Update version number in DESCRIPTION and update documentation using:
```{r updater, eval=FALSE, include=TRUE}
devtools::document(roclets = c('rd', 'collate', 'namespace'))
```
Error: Could not find package root. Is your working directory inside a package?

I wasn't sure how to resolve this one, I've never seen an error like this before.
The subsequent code chunks wouldn't run either, I'm guessing because of the issue here. 

Other than that everything ran smooth. 

I did not notice that when saving the rasters as .tifs as part of running 0_update_cold_pool_index.Rmd, everything turned out black and white though. I don't know if that's just an issue with the file size or something though, I've had issues saving complex files as tiffs before as well...

No issues running 1_cold_pool_index.Rmd and those plots came out looking great.

**Comment by sean-rohan-NOAA** [comment]
@Lukas-DeFilippo-NOAA Thank you for reviewing! From what I can tell there are no new issues.

- The select_years argument issue in interpolation_wrapper should be resolved in the most recent update where 1982,year(Sys.Date()) has been changed to 1982:year(Sys.Date()).
- 
- The error stand noted is due to the needing to run the package from the local directory containing the coldpool package. It creates a new version of sysdata.rda, the file that contains the built-in data product, in the R file path. After pushing to remote, the package is then updated. The idea here is that the package and data product are self-updating so code should be run from the directory containing the package

- The last error with devtools::document is due to the code not being run from the locally cloned directory. Same rationale as above with sysdata.rda.
